// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteAuvo.Infra.Data;

#nullable disable

namespace TesteAuvo.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230606020832_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("TesteAuvo.Domain.Entities.BookEmployeeTimeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectiveMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EffectiveYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("BookEmployeeTimeRecords");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.EmployeeTimeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookEmployeeTimeRecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ExitTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("HourlyRate")
                        .HasColumnType("REAL");

                    b.Property<TimeOnly>("LunchPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("LunchPeriodStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookEmployeeTimeRecordId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTimeRecords");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AbsentDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DebitHours")
                        .HasColumnType("REAL");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtraDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MissingHoursDeduction")
                        .HasColumnType("REAL");

                    b.Property<double>("OvertimeHours")
                        .HasColumnType("REAL");

                    b.Property<double>("OvertimePayment")
                        .HasColumnType("REAL");

                    b.Property<Guid>("TimeSheetClosureId")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalEarnings")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkedDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TimeSheetClosureId");

                    b.ToTable("PaymentOrders");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.TimeSheetClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookEmployeeTimeRecordId")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalDeductions")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalOvertime")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPayment")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BookEmployeeTimeRecordId")
                        .IsUnique();

                    b.ToTable("TimeSheetClosures");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.BookEmployeeTimeRecord", b =>
                {
                    b.HasOne("TesteAuvo.Domain.Entities.Department", "Department")
                        .WithMany("BookEmployeeTimeRecords")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.EmployeeTimeRecord", b =>
                {
                    b.HasOne("TesteAuvo.Domain.Entities.BookEmployeeTimeRecord", "BookEmployeeTimeRecord")
                        .WithMany("EmployeeTimeRecords")
                        .HasForeignKey("BookEmployeeTimeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteAuvo.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeTimeRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookEmployeeTimeRecord");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.PaymentOrder", b =>
                {
                    b.HasOne("TesteAuvo.Domain.Entities.Employee", "Employee")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteAuvo.Domain.Entities.TimeSheetClosure", "TimeSheetClosure")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("TimeSheetClosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TimeSheetClosure");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.TimeSheetClosure", b =>
                {
                    b.HasOne("TesteAuvo.Domain.Entities.BookEmployeeTimeRecord", "BookEmployeeTimeRecord")
                        .WithOne("TimeSheetClosure")
                        .HasForeignKey("TesteAuvo.Domain.Entities.TimeSheetClosure", "BookEmployeeTimeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookEmployeeTimeRecord");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.BookEmployeeTimeRecord", b =>
                {
                    b.Navigation("EmployeeTimeRecords");

                    b.Navigation("TimeSheetClosure");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.Department", b =>
                {
                    b.Navigation("BookEmployeeTimeRecords");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeTimeRecords");

                    b.Navigation("PaymentOrders");
                });

            modelBuilder.Entity("TesteAuvo.Domain.Entities.TimeSheetClosure", b =>
                {
                    b.Navigation("PaymentOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
